### PR TITLE
Add PyYAML 3.12

### PR DESCRIPTION
**Pull request by stoivo**
Not sure if you need to recreate the tag.

### CODE REVIEW

**Comment by FichteFoll** [comment]
I'm pretty sure the changes from relative to absolute imports will break at least in ST3 since the `st{2,3}/yaml` dir is _not_ added to `sys.path`. Did you verify that this works?

**Comment by stoivo** [comment]
No, I did not check. I just followed these steps. 

I work on GitSavvy and am going to use pyyaml dependence. I will check if this work today or tomorrow. 

Also can I rename `st3` to `all` and remove `st2`?

**Comment by FichteFoll** [comment]
Afaik the two distributed versions are incompatible between Python 2 and 3.

Is there a specific feature from 3.12 that you need? Otherwise you'll be perfectly fine with 3.11. A couple libraries have been updated upstream since the last time I mirrored them here, so I might do them all at once at some point. So far, nobody has needed any of the new features however, afaik.

**Comment by stoivo** [comment]
I don't have any feature on 3.12 I need so I will close it, so we will stick to 3.11 then.

**Comment by FichteFoll** [comment]
I just pulled 3.12 from upstream. The actual changes were negligible.

**Comment by stoivo** [comment]
Cool

**Pull request closed without merging**
